### ISSUE TITLE
What is the license ?

### ISSUE THREAD

**Issue by linuxenko** [jvalrog/atmega-adc#1]
Hi ! 
I want to make a simple project under GPLv3. I'm using this library for the project (I should admit it is awesome and saves time, btw it seems to work with atmega8). Could you please provide any information regard license of the `atmega-adc` ?

Thanks

**Comment by jvalrog** [comment]
Hello, I just added the LICENSE file (GPLv3) to the repository. Initially it was GPLv2 but I read that it's not compatible with the GPLv3, so I changed it.

Regards

**Comment by linuxenko** [comment]
Thank you )
